name: webkit_inspection_protocol
version: 0.7.3
description: A client for the Chrome DevTools Protocol (previously called the Webkit Inspection Protocol).
homepage: https://github.com/google/webkit_inspection_protocol.dart

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  logging: ^0.11.0

dev_dependencies:
  args: '>=0.13.0 <2.0.0'
  shelf: ^0.7.0
  shelf_static: ^0.2.0
  shelf_web_socket: ^0.2.0
  test: ^1.0.0
  webdriver: ^2.0.0
