name: webkit_inspection_protocol
version: 0.4.2
description: A client for the Webkit Inspection Protocol (WIP).

homepage: https://github.com/google/webkit_inspection_protocol.dart
authors:
- Devon Carew <devoncarew@google.com>
- Marc Fisher <fisherii@google.com>

environment:
  sdk: '>=2.0.0-dev.54.0 <3.0.0'

dependencies:
  args: '>=0.13.0 <2.0.0'
  logging: ^0.11.0
  shelf: ^0.7.0
  shelf_web_socket: ^0.2.0
dev_dependencies:
  shelf_static: ^0.2.0
  test: ^1.0.0
